apiVersion: v2
name: developer-portal-backend
description: A Helm chart for deploying the Diamond developer portal backend
type: application
version: 0.2.1
appVersion: 0.0.28
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.23.0
